package dji.sampleV5.aircraft.mavlink

import kotlin.math.roundToInt
import kotlin.math.roundToLong
import kotlin.math.sqrt

/**
 * Payload builders for the phase-1 telemetry set.
 *
 * Every builder lists the wire field order in a comment above it. That order is not editorial: it
 * is generated by MAVLink from the message definition (base fields sorted by descending type size,
 * ties broken by declaration order, then extension fields in declaration order) and appending in
 * any other order corrupts every field after the mistake without any checksum complaining. The
 * orders here were generated from upstream `common.xml`.
 */
internal object MavlinkMessages {

    private const val DEG_TO_E7 = 1e7
    private const val M_TO_MM = 1000.0
    private const val MPS_TO_CMPS = 100.0
    private const val DEG_TO_CDEG = 100.0
    private const val DEG_TO_RAD = Math.PI / 180.0

    /** custom_mode(u32), type(u8), autopilot(u8), base_mode(u8), system_status(u8), mavlink_version(u8) */
    fun heartbeat(snapshot: MavlinkSnapshot): ByteArray {
        val mode = MavlinkFlightMode.fromDjiMode(snapshot.flightMode, snapshot.manualOverrideActive)

        // Only flags backed by something real. GUIDED is reported when an autonomous mode is
        // actually flying the aircraft; MANUAL_INPUT when the pilot has the sticks.
        var baseMode = Mav.MODE_FLAG_CUSTOM_MODE_ENABLED
        if (snapshot.motorsRunning) baseMode = baseMode or Mav.MODE_FLAG_SAFETY_ARMED
        if (mode.guided) baseMode = baseMode or Mav.MODE_FLAG_GUIDED_ENABLED
        if (mode.manualInput) baseMode = baseMode or Mav.MODE_FLAG_MANUAL_INPUT_ENABLED
        if (snapshot.satelliteCount > GPS_STABILIZED_SATELLITES) {
            baseMode = baseMode or Mav.MODE_FLAG_STABILIZE_ENABLED
        }

        val systemStatus = when {
            snapshot.motorsRunning -> Mav.STATE_ACTIVE
            snapshot.flightMode == "UNKNOWN" -> Mav.STATE_UNINIT
            else -> Mav.STATE_STANDBY
        }

        return PayloadWriter()
            .u32(mode.customMode.toLong())
            .u8(Mav.TYPE_QUADROTOR)
            .u8(Mav.AUTOPILOT_INVALID)
            .u8(baseMode)
            .u8(systemStatus)
            .u8(Mav.MAVLINK_VERSION)
            .build()
    }

    /**
     * present(u32), enabled(u32), health(u32), load(u16), voltage_battery(u16),
     * current_battery(i16), drop_rate_comm(u16), errors_comm(u16), errors_count1..4(u16),
     * battery_remaining(i8)
     */
    fun sysStatus(snapshot: MavlinkSnapshot): ByteArray {
        var sensors = Mav.SENSOR_3D_GYRO or Mav.SENSOR_3D_ACCEL or Mav.SENSOR_3D_MAG or
            Mav.SENSOR_ABSOLUTE_PRESSURE or Mav.SENSOR_ATTITUDE_STABILIZATION or
            Mav.SENSOR_YAW_POSITION or Mav.SENSOR_Z_ALTITUDE_CONTROL or
            Mav.SENSOR_XY_POSITION_CONTROL or Mav.SENSOR_BATTERY
        val gpsHealthy = snapshot.satelliteCount >= GPS_FIX_3D_SATELLITES
        sensors = sensors or Mav.SENSOR_GPS

        val health = if (gpsHealthy) sensors else sensors and Mav.SENSOR_GPS.inv()

        return PayloadWriter()
            .u32(sensors.toLong())
            .u32(sensors.toLong())
            .u32(health.toLong())
            .u16(0) // load: not measured
            .u16(0) // voltage_battery: not read from the SDK yet, 0 = unknown
            .i16(-1) // current_battery: unknown
            .u16(0) // drop_rate_comm
            .u16(0) // errors_comm
            .u16(0).u16(0).u16(0).u16(0)
            .i8(snapshot.batteryPercent.coerceIn(MavlinkSnapshot.INVALID_BATTERY, PERCENT_MAX))
            .build()
    }

    /**
     * time_usec(u64), lat(i32), lon(i32), alt(i32), eph(u16), epv(u16), vel(u16), cog(u16),
     * fix_type(u8), satellites_visible(u8)
     */
    fun gpsRawInt(snapshot: MavlinkSnapshot, timeUsec: Long): ByteArray {
        val groundSpeed = groundSpeedMps(snapshot)
        return PayloadWriter()
            .u64(timeUsec)
            .i32(degToE7(snapshot.latitudeDeg))
            .i32(degToE7(snapshot.longitudeDeg))
            .i32(metresToMm(snapshot.altitudeAslM))
            // DJI does not expose HDOP/VDOP, so both are reported unknown rather than guessed.
            .u16(MavlinkSnapshot.UINT16_UNKNOWN)
            .u16(MavlinkSnapshot.UINT16_UNKNOWN)
            .u16((groundSpeed * MPS_TO_CMPS).roundToInt().coerceIn(0, MavlinkSnapshot.UINT16_UNKNOWN))
            .u16(headingCdeg(snapshot.headingDeg))
            .u8(gpsFixType(snapshot.satelliteCount))
            .u8(snapshot.satelliteCount.coerceIn(0, U8_MAX))
            .build()
    }

    /** time_boot_ms(u32), roll(f), pitch(f), yaw(f), rollspeed(f), pitchspeed(f), yawspeed(f) */
    fun attitude(snapshot: MavlinkSnapshot, timeBootMs: Long): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .f32((snapshot.rollDeg * DEG_TO_RAD).toFloat())
            .f32((snapshot.pitchDeg * DEG_TO_RAD).toFloat())
            .f32((wrapPi(snapshot.yawDeg) * DEG_TO_RAD).toFloat())
            // Angular rates are not exposed by the DJI SDK telemetry WildBridge reads.
            .f32(0f).f32(0f).f32(0f)
            .build()

    /**
     * time_boot_ms(u32), lat(i32), lon(i32), alt(i32), relative_alt(i32),
     * vx(i16), vy(i16), vz(i16), hdg(u16)
     */
    fun globalPositionInt(snapshot: MavlinkSnapshot, timeBootMs: Long): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .i32(degToE7(snapshot.latitudeDeg))
            .i32(degToE7(snapshot.longitudeDeg))
            .i32(metresToMm(snapshot.altitudeAslM))
            .i32(metresToMm(snapshot.altitudeAglM))
            .i16(mpsToCmps(snapshot.velocityNorthMps))
            .i16(mpsToCmps(snapshot.velocityEastMps))
            .i16(mpsToCmps(snapshot.velocityDownMps))
            .u16(headingCdeg(snapshot.headingDeg))
            .build()

    /** airspeed(f), groundspeed(f), alt(f), climb(f), heading(i16), throttle(u16) */
    fun vfrHud(snapshot: MavlinkSnapshot): ByteArray {
        val groundSpeed = groundSpeedMps(snapshot)
        return PayloadWriter()
            // DJI reports no airspeed; ground speed is repeated, as RosettaDrone also does, and
            // this is documented rather than silently implied.
            .f32(groundSpeed.toFloat())
            .f32(groundSpeed.toFloat())
            .f32(snapshot.altitudeAslM.toFloat())
            // MAVLink climb rate is positive up; DJI's z velocity is positive down.
            .f32((-snapshot.velocityDownMps).toFloat())
            .i16(((snapshot.headingDeg % FULL_CIRCLE_DEG + FULL_CIRCLE_DEG) % FULL_CIRCLE_DEG).roundToInt())
            .u16(0) // throttle: not exposed
            .build()
    }

    /**
     * current_consumed(i32), energy_consumed(i32), temperature(i16), voltages(u16[10]),
     * current_battery(i16), id(u8), battery_function(u8), type(u8), battery_remaining(i8),
     * [ext] time_remaining(i32)
     *
     * `time_remaining` is a MAVLink 2 extension field — it is the reason WildBridge's
     * `remainingFlightTime` has a standard home at all, and it could not have been added under
     * MAVLink 1.
     */
    fun batteryStatus(snapshot: MavlinkSnapshot): ByteArray =
        PayloadWriter()
            .i32(-1) // current_consumed: unknown
            .i32(-1) // energy_consumed: unknown
            .i16(MavlinkSnapshot.INT16_UNKNOWN) // temperature: unknown
            // Per-cell voltages are not read from the SDK; UINT16_MAX is the documented "unknown".
            .u16Array(MavlinkSnapshot.UINT16_UNKNOWN, VOLTAGE_CELLS)
            .i16(-1) // current_battery: unknown
            .u8(0) // id
            .u8(0) // battery_function: UNKNOWN
            .u8(0) // type: UNKNOWN
            .i8(snapshot.batteryPercent.coerceIn(MavlinkSnapshot.INVALID_BATTERY, PERCENT_MAX))
            .i32(snapshot.remainingFlightTimeS.coerceAtLeast(0))
            .build()

    /**
     * latitude(i32), longitude(i32), altitude(i32), x(f), y(f), z(f), q(f[4]),
     * approach_x(f), approach_y(f), approach_z(f)
     */
    fun homePosition(snapshot: MavlinkSnapshot): ByteArray =
        PayloadWriter()
            .i32(degToE7(snapshot.homeLatitudeDeg))
            .i32(degToE7(snapshot.homeLongitudeDeg))
            .i32(metresToMm(snapshot.homeAltitudeAslM))
            .f32(0f).f32(0f).f32(0f) // local x/y/z: no local frame is maintained
            .f32Array(IDENTITY_QUATERNION, QUATERNION_LENGTH)
            .f32(0f).f32(0f).f32(0f) // approach vector: not defined
            .build()

    /**
     * capabilities(u64), uid(u64), flight_sw_version(u32), middleware_sw_version(u32),
     * os_sw_version(u32), board_version(u32), vendor_id(u16), product_id(u16),
     * flight_custom_version(u8[8]), middleware_custom_version(u8[8]), os_custom_version(u8[8])
     *
     * Only capabilities that are actually implemented are advertised. Claiming MISSION_INT or FTP
     * before they exist is the same class of mistake as claiming the wrong autopilot.
     */
    fun autopilotVersion(): ByteArray =
        PayloadWriter()
            .u64(Mav.CAP_MAVLINK2)
            .u64(0) // uid
            .u32(0).u32(0).u32(0).u32(0)
            .u16(0).u16(0)
            .zeros(CUSTOM_VERSION_BYTES * 3)
            .build()

    /** severity(u8), text(char[50]) */
    fun statusText(severity: Int, text: String): ByteArray =
        PayloadWriter()
            .u8(severity)
            .chars(text, STATUSTEXT_LENGTH)
            .build()

    // ---- conversions -------------------------------------------------------

    fun groundSpeedMps(snapshot: MavlinkSnapshot): Double =
        sqrt(
            snapshot.velocityNorthMps * snapshot.velocityNorthMps +
                snapshot.velocityEastMps * snapshot.velocityEastMps
        )

    /** MAVLink GPS fix type, from satellite count — DJI reports no fix type directly. */
    fun gpsFixType(satelliteCount: Int): Int = when {
        satelliteCount >= GPS_FIX_3D_SATELLITES -> GPS_FIX_TYPE_3D
        satelliteCount >= GPS_FIX_2D_SATELLITES -> GPS_FIX_TYPE_2D
        else -> GPS_FIX_TYPE_NO_FIX
    }

    private fun degToE7(degrees: Double): Int = (degrees * DEG_TO_E7).roundToLong().toInt()

    private fun metresToMm(metres: Double): Int = (metres * M_TO_MM).roundToLong().toInt()

    private fun mpsToCmps(mps: Double): Int =
        (mps * MPS_TO_CMPS).roundToInt().coerceIn(Short.MIN_VALUE.toInt(), Short.MAX_VALUE.toInt())

    /** Heading in centidegrees, 0..35999, as GLOBAL_POSITION_INT and GPS_RAW_INT expect. */
    private fun headingCdeg(headingDeg: Double): Int {
        val normalised = ((headingDeg % FULL_CIRCLE_DEG) + FULL_CIRCLE_DEG) % FULL_CIRCLE_DEG
        return (normalised * DEG_TO_CDEG).roundToInt().coerceIn(0, MAX_CDEG)
    }

    /** DJI reports yaw in -180..180 already, but normalise so ATTITUDE never exceeds ±pi. */
    private fun wrapPi(degrees: Double): Double {
        var value = (degrees + HALF_CIRCLE_DEG) % FULL_CIRCLE_DEG
        if (value < 0) value += FULL_CIRCLE_DEG
        return value - HALF_CIRCLE_DEG
    }

    private const val GPS_FIX_TYPE_NO_FIX = 0
    private const val GPS_FIX_TYPE_2D = 2
    private const val GPS_FIX_TYPE_3D = 3
    private const val GPS_FIX_2D_SATELLITES = 4
    private const val GPS_FIX_3D_SATELLITES = 6
    private const val GPS_STABILIZED_SATELLITES = 5
    private const val PERCENT_MAX = 100
    private const val U8_MAX = 255
    private const val VOLTAGE_CELLS = 10
    private const val QUATERNION_LENGTH = 4
    private const val CUSTOM_VERSION_BYTES = 8
    private const val STATUSTEXT_LENGTH = 50
    private const val FULL_CIRCLE_DEG = 360.0
    private const val HALF_CIRCLE_DEG = 180.0
    private const val MAX_CDEG = 35999
    private val IDENTITY_QUATERNION = floatArrayOf(1f, 0f, 0f, 0f)
}
